### ISSUE TITLE
Players able to use ansi code and troll console

### ISSUE THREAD

**Issue by DryByte** [SpadesX/SpadesX#38]
**Description:**
- Any player can troll the console using ANSI Code, like: \033[2J or \033[31;5m. (Maybe can be fixed using iscntrl()?)

**How to reproduce:**
- Start the server, join and send a message with any ANSI code or just set your nickname to it.

**Comment by Haxk20** [comment]
Very nice find

**Comment by Haxk20** [comment]
Fixed in: 67bef30306b199867311c4628f0053e24206eda0

Also added checks to let players use colored chat.

**Comment by DryByte** [comment]
Bug still on there, this is the code im using:

```js
const AoS = require("aos.js");
let client = new AoS.Client({name: "\033[31;5m"});

client.on("connect", () => {
	console.log("Client connected to the server!");
});

client.on("StateData", (fields) => {
	client.joinGame();

	setInterval(() => {
		client.sendMessage("/\033[2J",0);
		client.sendMessage("\033[2J",0);
	}, 500);
});

client.on("ChatMessage", (fields) => {
	console.log(fields);
});

client.connect("aos://127.0.0.1:32887");
```

**Comment by DryByte** [comment]
Sorry for the last message, forgot to recompile :facepalm: . But, the bug still on there for character name.

**Comment by Haxk20** [comment]
Yep character names i will fix tomorrow :)

**Comment by Haxk20** [comment]
Fixed in: 4a0a923ab408e4bbb5730f9cfce73fe03569ee91

**Comment by DryByte** [comment]
Server is crashing with segment fault in my side, when trying to join in a team with the ansi nickname

**Comment by Haxk20** [comment]
Will check later. Probably screwed up some memory access. Tho it is 3am nearly so...

**Comment by DryByte** [comment]
ok kekw

**Comment by Haxk20** [comment]
Should be fully fixed in latest commit
